kind: Service                             
apiVersion: v1
metadata:
  name: kuberapp
  labels:
    app: kuberapp
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: kuberapp                    
  type: LoadBalancer 
